version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=fastapi
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
      - DATABASE_HOSTNAME=postgres
      - SECRET_KEY=ddeab7bb0845789569c3f948b345766ac01ff204cbe3fc5b99092fe117135237
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
